### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by MohammadHadiAlizadeh** [OpenModelica/OMMatlab#13]
Hello,
I want to use OMMATLAB for the first time. I've just followed the procedure, but I get an error when I want to test the interference.

![image](https://user-images.githubusercontent.com/88594092/178303672-901c965a-38d9-4ecb-ad7e-cdd6387d4fb0.png)

**Comment by arun3688** [comment]
@MohammadHadiAlizadeh where did you install your `OpenModelica `

**Comment by MohammadHadiAlizadeh** [comment]
> @MohammadHadiAlizadeh where did you install your `OpenModelica `

This is the installation path.     
C:\Program Files\OpenModelica1.19.2-64bit

**Comment by arun3688** [comment]
@MohammadHadiAlizadeh can you change the location of your OpenModelica installation to `C:/OpenModelica1.19.2-64bit`, because the main problem is there is a space between `Program Files` changing the location would fix the problem, otherwise you can try to do the following, try to explicitly specify the path when creating the session something like below

`omc = OMMatlab("C:/OpenModelica/build/bin/omc.exe")`

**Comment by adrpo** [comment]
@arun3688 we can fix this by just adding quotes round the executable path in here:
https://github.com/OpenModelica/OMMatlab/blob/master/OMMatlab.m#L73

`cmd = ['START /b ',' \"',omhomepath,'\" --interactive=zmq -z=matlab.',randomstring];`

 Note that I have no idea about Matlab and if you need to escape the quotes or not! You can find that out.

**Comment by MohammadHadiAlizadeh** [comment]
> @MohammadHadiAlizadeh can you change the location of your OpenModelica installation to `C:/OpenModelica1.19.2-64bit`, because the main problem is there is a space between `Program Files` changing the location would fix the problem, otherwise you can try to do the following, try to explicitly specify the path when creating the session something like below
> 
> `omc = OMMatlab("C:/OpenModelica/build/bin/omc.exe")`

Thanks. I fixed it.
